[package]
name = "metafile"
description = "Convenient composition API for metafile-rs parsers and renderers"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
metafile-core = { path = "../metafile-core" }
metafile-svg = { path = "../metafile-svg" }
metafile-wmf = { path = "../metafile-wmf" }
serde.workspace = true

[dev-dependencies]
serde_json = "1"

[lints]
workspace = true
