[package]
name = "metafile-wmf"
description = "First-party safe WMF parser, inspection, and renderer-independent playback engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
encoding_rs.workspace = true
metafile-core = { path = "../metafile-core", version = "1.0.1" }
metafile-dib = { path = "../metafile-dib", version = "1.0.1" }
serde.workspace = true

[dev-dependencies]
metafile-svg = { path = "../metafile-svg", version = "1.0.1" }

[lints]
workspace = true
